apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-08T06:18:03Z
  generation: 1
  labels:
    run: nn-deployment-1
  name: nn-deployment-1
  namespace: default
  resourceVersion: "1153"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nn-deployment-1
  uid: ee74ab12-4169-11e9-a6dd-42010a800147
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nn-deployment-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nn-deployment-1
    spec:
      containers:
      - image: gcr.io/newton-joshua-com/newton-joshua:v1
        imagePullPolicy: IfNotPresent
        name: nn-deployment-1
        ports:
        - containerPort: 6006
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-08T06:18:03Z
    lastUpdateTime: 2019-03-08T06:18:03Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1