apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nn-deployment-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: newton-joshua
    spec:
      containers:
      - image: gcr.io/newton-joshua-com/newton-joshua:v1
        imagePullPolicy: Always
        name: newton-joshua-website
        ports:
        - containerPort: 6006
          protocol: TCP
        resources: {}